apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentiment-analysis-app
  labels:
    app: sentiment-analysis
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sentiment-analysis
  template:
    metadata:
      labels:
        app: sentiment-analysis
    spec:
      containers:
      - name: sentiment-analysis-app
        image: IMAGE_TO_REPLACE
        ports:
        - containerPort: 5000
        env:
        - name: CAPSTONE_TEST
          valueFrom:
            secretKeyRef:
              name: capstone-secret
              key: CAPSTONE_TEST
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /gcp/key.json
        volumeMounts:
        - name: gcp-key-volume
          mountPath: /gcp
          readOnly: true
      volumes:
      - name: gcp-key-volume
        secret:
          secretName: gcp-sa-key
---
apiVersion: v1
kind: Service
metadata:
  name: sentiment-analysis-service
spec:
  selector:
    app: sentiment-analysis
  ports:
  - port: 80
    targetPort: 5000
  type: LoadBalancer
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sentiment-analysis-monitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: sentiment-analysis
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
