apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentiment-analysis-app
  labels:
    app: sentiment-analysis
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sentiment-analysis
  template:
    metadata:
      labels:
        app: sentiment-analysis
    spec:
      volumes:
      - name: flask-app-volume
        configMap:
          name: flask-app
      containers:
      - name: sentiment-analysis-app
        volumeMounts:
        - name: flask-app-volume
          mountPath: /app
        image: python:3.8-slim
        command: ["/bin/bash", "-c"]
        args: ["pip install flask && python /app/app.py"]
        env:
        - name: PORT
          value: "5000"
        - name: FLASK_ENV
          value: "production"
        ports:
        - containerPort: 5000
          name: http
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: sentiment-analysis-service
  labels:
    app: sentiment-analysis
spec:
  selector:
    app: sentiment-analysis
  ports:
  - port: 80
    targetPort: 5000
    name: http
  type: LoadBalancer

