apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sentiment-analysis-monitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: sentiment-analysis
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
